[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyshort"
version = "1.0.0"
description = "Raccourcisseur d'URLs en ligne de commande"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "typer>=0.12.0",
    "httpx>=0.27.0",
    "pyperclip>=1.8.2",
    "rich>=13.7.0",
]

[project.scripts]
pyshort     = "pyshort.cli:app"
pyshort-gui = "pyshort.gui:launch_gui"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-dir]
"" = "."